# Generated by Django 3.2.9 on 2021-12-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zipcode', models.IntegerField()),
                ('num', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('option', models.CharField(max_length=120)),
                ('selectfile', models.FileField(upload_to='Myfiles')),
                ('disc', models.TextField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
